### ISSUE TITLE
Create interfaces and exceptions

### ISSUE THREAD

**Issue by Trizax350** [Trizax350/Software-Testing-Group-6#5]
Please create service folder into core modul (next to the model) and create interfaces like:
- LoginInterface
- UserInterfaces (User, Student, Teacher, Administrator)
Create exceptions like:
- RequestAlreadyCreated (Student)
- ComplainAlreadyExist (Student)
- RequestTypeAlreadyExist (Administrator)

**Comment by prenoo** [comment]
I've created the classes, but it's mostly empty for now.

**Comment by hinaghous** [comment]
you have already created the interfaces and you said you will delete few of them that are of no use, so did you delet them?

**Comment by prenoo** [comment]
I've deleted the unnecessary ones, and started coding the method signatures in some of the interfaces.

**Comment by Solyom2** [comment]
I deleted the teacher, student and administrator interface, we decided that the UserInterface will contain the abstract methods related to these classes.
